gcc-c++11:
  script: "CI/ci-linux.sh gcc C++11"

clang-c++11:
  script: "CI/ci-linux.sh clang C++11"

gcc-c++98:
  script: "CI/ci-linux.sh gcc C++98"

clang-c++98:
  script: "CI/ci-linux.sh clang C++98"

