#-----------  Job Informations:
# Type:       Build: {{BUILDTYPE}}
# OS:         Linux
# Compiler:   {{COMPILER}}
# Language:   {{LANGUAGE}}
# QT Version: {{QT_VERSION}}

build-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QT_VERSION}}:
  stage: build
  script: "CI/ci-linux-build.sh {{COMPILER}} {{LANGUAGE}} {{BUILDTYPE}} {{QT_VERSION}}"
  #image: graphics.rwth-aachen.de:4567/docker/docker/docker-openmesh-container
  tags:
    - Linux
    - stretch
  artifacts:
    paths:
    - build-{{COMPILER}}-{{LANGUAGE}}-{{QT_VERSION}}-{{BUILDTYPE}}/
